/**
 * Adjacent states and provinces in North America, by abbreviation.
 * U.S. and Canadian states, provinces, and territories are given by their
 * 2-letter abbreviations. Mexican States are given by their 2-letter
 * abbreviations prefixed with the letter 'm'.
 */

export const stateAdjacencies: Record<string, string[]> = {
  // U.S. States
  AL: ['TN', 'GA', 'FL', 'MS'],
  AK: ['YT', 'BC'],
  AR: ['MO', 'TN', 'MS', 'LA', 'TX', 'OK'],
  AZ: ['UT', 'CO', 'NM', 'CA', 'NV', 'mSO'],
  CA: ['OR', 'NV', 'AZ', 'mBC'],
  CO: ['WY', 'NE', 'KS', 'OK', 'NM', 'AZ', 'UT'],
  CT: ['MA', 'RI', 'NY'],
  DC: ['MD', 'VA'],
  DE: ['PA', 'NJ', 'MD'],
  FL: ['GA', 'AL'],
  GA: ['NC', 'SC', 'FL', 'AL', 'TN'],
  HI: [],
  IA: ['MN', 'WI', 'IL', 'MO', 'NE', 'SD'],
  ID: ['MT', 'WY', 'UT', 'NV', 'OR', 'WA', 'BC'],
  IL: ['WI', 'IN', 'KY', 'MO', 'IA', 'MI'],
  IN: ['MI', 'OH', 'KY', 'IL'],
  KS: ['NE', 'MO', 'OK', 'CO'],
  KY: ['OH', 'WV', 'VA', 'TN', 'MO', 'IL', 'IN'],
  LA: ['AR', 'MS', 'TX'],
  MA: ['NH', 'RI', 'CT', 'NY', 'VT'],
  MD: ['PA', 'DE', 'DC', 'VA', 'WV'],
  ME: ['NH', 'QC', 'NB', 'NS'],
  MI: ['OH', 'IN', 'WI', 'IL', 'MN', 'ON'],
  MN: ['WI', 'IA', 'SD', 'ND', 'MI', 'MB', 'ON'],
  MO: ['IA', 'IL', 'KY', 'TN', 'AR', 'OK', 'KS', 'NE'],
  MS: ['TN', 'AL', 'LA', 'AR'],
  MT: ['ND', 'SD', 'WY', 'ID', 'BC', 'AB', 'SK'],
  NC: ['VA', 'SC', 'GA', 'TN'],
  ND: ['MN', 'SD', 'MT', 'SK', 'MB'],
  NE: ['SD', 'IA', 'MO', 'KS', 'CO', 'WY'],
  NH: ['ME', 'MA', 'VT', 'QC'],
  NJ: ['NY', 'DE', 'PA'],
  NM: ['CO', 'OK', 'TX', 'AZ', 'UT', 'mCH', 'mSO'],
  NV: ['ID', 'UT', 'AZ', 'CA', 'OR'],
  NY: ['VT', 'MA', 'CT', 'NJ', 'PA', 'RI', 'ON', 'QC'],
  OH: ['PA', 'WV', 'KY', 'IN', 'MI', 'ON'],
  OK: ['KS', 'MO', 'AR', 'TX', 'NM', 'CO'],
  OR: ['WA', 'ID', 'NV', 'CA'],
  PA: ['NY', 'NJ', 'DE', 'MD', 'WV', 'OH', 'ON'],
  RI: ['MA', 'CT', 'NY'],
  SC: ['NC', 'GA'],
  SD: ['ND', 'MN', 'IA', 'NE', 'WY', 'MT'],
  TN: ['KY', 'VA', 'NC', 'GA', 'AL', 'MS', 'AR', 'MO'],
  TX: ['OK', 'AR', 'LA', 'NM', 'mCH', 'mCO', 'mNL', 'mTM'],
  UT: ['ID', 'WY', 'CO', 'NM', 'AZ', 'NV'],
  VA: ['MD', 'DC', 'NC', 'TN', 'KY', 'WV'],
  VT: ['NH', 'MA', 'NY', 'QC'],
  WA: ['ID', 'OR', 'BC'],
  WI: ['MI', 'IL', 'IA', 'MN'],
  WV: ['PA', 'MD', 'VA', 'KY', 'OH'],
  WY: ['MT', 'SD', 'NE', 'CO', 'UT', 'ID'],
  // U.S. Territories
  AS: [],
  FM: ['GU', 'MP', 'MH'],
  GU: ['MP', 'FM'],
  MH: ['FM'],
  MP: ['GU', 'FM'],
  PR: ['VI'],
  PW: [],
  VI: ['PR'],
  // Canadian Provinces and Territories
  AB: ['BC', 'NT', 'SK', 'MT'],
  BC: ['YT', 'NT', 'AB', 'AK', 'WA', 'ID', 'MT'],
  MB: ['SK', 'NU', 'ON', 'ND', 'MN'],
  NB: ['QC', 'PE', 'NS', 'ME'],
  NL: ['QC', 'NS'],
  NT: ['YT', 'BC', 'AB', 'SK', 'NU'],
  NS: ['NB', 'PE', 'NL', 'ME'],
  NU: ['NT', 'MB', 'ON', 'QC'],
  ON: ['MB', 'NU', 'QC', 'MN', 'MI', 'OH', 'PA', 'NY'],
  PE: ['NB', 'NS', 'QC'],
  QC: ['NU', 'ON', 'NB', 'PE', 'NL', 'NY', 'VT', 'NH', 'ME'],
  SK: ['AB', 'NT', 'MB', 'MT', 'ND'],
  YT: ['NT', 'BC', 'AK'],
  // Mexican States and Districts
  mAG: ['mZA', 'mJA'],
  mBC: ['mBS', 'mSO', 'CA'],
  mBS: ['mBC', 'mSO', 'mSI'],
  mCH: ['mSO', 'mSI', 'mDG', 'mCO', 'NM', 'TX'],
  mCL: ['mJA', 'mMI'],
  mCM: ['mTB', 'mYU', 'mQR'],
  mCO: ['mCH', 'mDG', 'mZA', 'mSL', 'mNL', 'mTM', 'TX'],
  mCS: ['mOA', 'mVE', 'mTB'],
  mDF: ['mME', 'mMO'],
  mDG: ['mSI', 'mCH', 'mCO', 'mZA', 'mNA'],
  mGR: ['mMI', 'mME', 'mMO', 'mPB', 'mOA'],
  mGT: ['mJA', 'mZA', 'mSL', 'mQE', 'mMI'],
  mHG: ['mQE', 'mSL', 'mVE', 'mPB', 'mTL', 'mME'],
  mJA: ['mNA', 'mZA', 'mAG', 'mSL', 'mGT', 'mCL', 'mMI'],
  mME: ['mMI', 'mQE', 'mHG', 'mTL', 'mPB', 'mMO', 'mGR', 'mDF'],
  mMI: ['mCL', 'mJA', 'mGT', 'mQE', 'mME', 'mGR'],
  mMO: ['mGR', 'mME', 'mPB', 'mDF'],
  mNA: ['mSI', 'mDG', 'mZA', 'mJA'],
  mNL: ['mCO', 'mTM', 'mZA', 'mSL', 'TX'],
  mOA: ['mGR', 'mPB', 'mVE', 'mCS'],
  mPB: ['mMO', 'mME', 'mTL', 'mHG', 'mVE', 'mOA', 'mGR'],
  mQE: ['mGT', 'mSL', 'mHG', 'mME', 'mMI'],
  mQR: ['mCM', 'mYU'],
  mSI: ['mBS', 'mSO', 'mCH', 'mDG', 'mNA'],
  mSL: ['mZA', 'mCO', 'mNL', 'mTM', 'mVE', 'mJA', 'mGT', 'mQE', 'mHG'],
  mSO: ['mBC', 'mBS', 'mCH', 'mSI', 'AZ', 'NM'],
  mTB: ['mVE', 'mCS', 'mCM'],
  mTL: ['mME', 'mPB', 'mHG'],
  mTM: ['mCO', 'mNL', 'mSL', 'mVE', 'TX'],
  mVE: ['mTM', 'mSL', 'mHG', 'mPB', 'mOA', 'mTB', 'mCS'],
  mYU: ['mCM', 'mQR'],
  mZA: ['mDG', 'mCO', 'mNL', 'mSL', 'mNA', 'mJA', 'mAG', 'mGT']
};
